package prog6112eaq1;

import javax.swing.JOptionPane;

/**
 *
 * @author Lindelo Nkosi 
 */
public class CartridgeUsage extends javax.swing.JFrame {

    /**
     * Creates new form CartridgeUsage
     */
    
     //we are making this a field so that we will be able to access values 
    Cartridge [][] CartridgeUsages;
    
    public CartridgeUsage() {
        initComponents();
        
         Cartridge [][] CartridgeUsages = {
            {new Cartridge("HP Deskjesk 650", "2018", 10), new Cartridge("HP Deskjesk 650", "2019", 35), new Cartridge("HP Deskjesk 650", "2020", 20) },
            {new  Cartridge("Epson K750", "2018", 15),  new  Cartridge("Epson K750", "2019", 22),   new  Cartridge("Epson K750", "2020", 12) },
            {new  Cartridge("Canon Z100", "2018", 30), new  Cartridge("Canon Z100", "2019", 31), new  Cartridge("Canon Z100", "2020", 33) }
        };
       this.CartridgeUsages = new Cartridge[CartridgeUsages.length][CartridgeUsages[0].length];
       
       
       for(int i = 0; i <CartridgeUsages.length; i++){
           for(int j = 0; j <CartridgeUsages[i].length; j++){
               this.CartridgeUsages[i][j] = new  Cartridge(CartridgeUsages[i][j]);
           }
       }
       
       
       String[] printerNames = new String[3];
       
       //gettin' names
       
       for(int i = 0; i <  CartridgeUsages.length; i++){
          for(int j = 0; j < CartridgeUsages[i].length; j++){
              
              printerNames[i] = CartridgeUsages[i][j].getPrinter();
           }
          } 
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(printerNames));
       
       
       String [] yearss = new String[3];
       
       //gettin' year
       
       yearss[0] = CartridgeUsages[0][0].getYear();
       yearss[1] = CartridgeUsages[1][1].getYear();
       yearss[2] = CartridgeUsages[1][2].getYear();
       
       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(yearss));
       }
    

       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Select Printer:");

        jLabel2.setText("Select Year: ");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        jMenuItem1.setText("Submit");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Yearly Usage");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: submit
        int printerNames = jComboBox1.getSelectedIndex();
        int priceBox = jComboBox2.getSelectedIndex();
        
        String names = this.CartridgeUsages[printerNames][priceBox].getPrinter();
        
        String year = this.CartridgeUsages[printerNames][priceBox].getYear();
        
        int usage = this.CartridgeUsages[printerNames][priceBox].getUsage();
        
        
        JOptionPane.showMessageDialog(null, " PRINTER: " + names + "\n" + "YEAR: " + year + "\n" + "USAGE: " + usage );
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
       int totalDeskjesk = 0;
       int epsonK = 0;
       int canon = 0;
       
      
        
      
        
        //for deskjeck
        
        for(int i = 0; i < this.CartridgeUsages.length; i++){
            for(int j = 0; j < this.CartridgeUsages[i].length; j++){
               totalDeskjesk += this.CartridgeUsages[0][j].getUsage(); 
            }
            break;
        }
        
        //for epsonK
        for(int i = 0; i < this.CartridgeUsages.length; i++){
            for(int j = 0; j < this.CartridgeUsages[i].length; j++){
              epsonK += this.CartridgeUsages[1][j].getUsage(); 
            }
           break; 
        }
        
        //FOR Canan
         for(int i = 0; i < this.CartridgeUsages.length; i++){
            for(int j = 0; j < this.CartridgeUsages[i].length; j++){
               canon += this.CartridgeUsages[2][j].getUsage();
            }
         break;   
        }
         JOptionPane.showMessageDialog(null, "Total cartridge usage for HP Deskjesk 650 is " + totalDeskjesk + "\n" 
                + "Total cartridge usage for EpsonK750 is "  +  epsonK + "\n" 
                + "Total cartridge usage for Canon Z100 is " + canon ); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartridgeUsage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartridgeUsage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartridgeUsage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartridgeUsage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartridgeUsage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
